Story3
iO-Academy/AcademyPortal pull request #336
Opened 2021-05-25 13:06 UTC by mariagus

Added tests and skipped tests for sanitisers and validators

2021-05-25 13:38 UTC, ashleycoles requested changes

2021-05-25 13:38 UTC, ashleycoles commented on composer.json
> +    "test": "phpunit -v"
Please remove this change - revert it back to just phpunit

2021-05-25 13:38 UTC, ashleycoles commented on tests/Validators/GithubEducationValidatorTest.php
> +        $url = ['i am an array'];
Nice to meet you array!

2021-05-25 13:52 UTC, ashleycoles approved these changes

2021-05-27 12:42 UTC, mporam approved these changes

2021-05-27 12:42 UTC, merged