Story1
iO-Academy/AcademyPortal pull request #351
Opened 2021-05-26 13:58 UTC by isabellecochrane

2021-05-26 14:26 UTC, ashleycoles submitted a review, later dismissed

2021-05-26 14:26 UTC, ashleycoles commented on templates/applicantForm.phtml
> +                    <select id="backgroundInfo" class="submitApplicant form-control" name="backgroundInfoId" required></select>
This field does not show the current value - other dropdown fields have a default option which is whatever is in the db for that applicant, can you set this up to do the same please.

To reproduce just edit an applicant, change their background to school leaver and save, then refresh. The background field will just show Changing careers

2021-05-26 14:26 UTC, ashleycoles commented on templates/applicantForm.phtml
> +
I seem to have an issue here where I'm getting the "Total payment is more than course price" error when doing this:![Screenshot 2021-05-26 at 15 14 50](https://user-images.githubusercontent.com/19924378/119675703-2f3cf400-be35-11eb-8cf3-dac1640d75dc.png)

2021-05-27 08:16 UTC, mporam requested changes

2021-05-27 08:16 UTC, mporam commented on src/Validators/ApplicantValidator.php
> +            ) > (int)$applicant['fee']
what if there is no applicant fee? its an optional field so if its blank, this validation should use the academyprice global instead

2021-05-27 09:59 UTC, mporam approved these changes

2021-05-27 12:38 UTC, merged